# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.IntegerField(default=0, max_length=11)),
                ('email', models.CharField(default=0, max_length=40)),
                ('phone', models.CharField(default=0, max_length=11)),
                ('qq', models.CharField(default=0, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
    ]
