# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
    ]
