# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180725_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次登录时间'),
        ),
    ]
