# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180729_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, default=0, max_length=40, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qq',
            field=models.CharField(blank=True, default=0, max_length=20, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '不设置'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
