# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180729_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='admin', max_length=30, verbose_name='昵称'),
        ),
    ]
