# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180726_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_introduce',
            name='goods',
        ),
        migrations.DeleteModel(
            name='goods_introduce',
        ),
    ]
