# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 10:28
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180726_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='商品介绍')),
                ('afte_sale', DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='售后')),
                ('goods', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
            options={
                'verbose_name': '商品介绍',
                'verbose_name_plural': '商品详细信息',
            },
        ),
    ]
