# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_img',
            name='goods',
        ),
        migrations.DeleteModel(
            name='goods_img',
        ),
    ]
