# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180726_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_evaluate',
            name='evaluate_star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='评价星级'),
        ),
        migrations.AlterField(
            model_name='goods_evaluate',
            name='evaluate_type',
            field=models.IntegerField(choices=[('差评', 1), ('中评', 2), ('好评', 3)], default=5, verbose_name='好评度'),
        ),
    ]
