# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180726_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_evaluate',
            name='evaluate_type',
            field=models.IntegerField(choices=[(1, '差评'), (2, '中评'), (3, '好评')], default=5, verbose_name='好评度'),
        ),
    ]
