# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20180726_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_tj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodstj_sort_id', models.IntegerField(default=1, max_length=32)),
                ('goodstj_start_time', models.DateTimeField()),
                ('goodstj_end_time', models.DateTimeField()),
                ('goodstj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品ID')),
            ],
        ),
    ]
