# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-28 20:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_goods_tj'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_introduce',
            name='content2',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品功能'),
        ),
        migrations.AddField(
            model_name='goods_introduce',
            name='content3',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品信息'),
        ),
        migrations.AddField(
            model_name='goods_introduce',
            name='content4',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品配置'),
        ),
        migrations.AlterField(
            model_name='goods_introduce',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品特色'),
        ),
        migrations.AlterField(
            model_name='goods_tj',
            name='goodstj_sort_id',
            field=models.IntegerField(default=1),
        ),
    ]
