# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-28 20:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20180728_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_introduce',
            name='content3',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品细节'),
        ),
        migrations.AlterField(
            model_name='goods_introduce',
            name='content4',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=10240000000000000, verbose_name='产品信息'),
        ),
    ]
