# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_remove_goods_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.goods_type', verbose_name='分类ID'),
        ),
    ]
