# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_goods_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='type_id',
            field=models.IntegerField(default=1, verbose_name='分类ID'),
        ),
    ]
